# Copyright (C) 2026 Ota
# Licensed under the Apache License, Version 2.0.

name: Ota governance

on:
  push:
    branches:
      - bobai/nopCommerce-ota-pressure
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify-native-linux:
    uses: ./.github/workflows/ota-verify-native-linux.yml
    with:
      ota_projection_identity: sha256:3edcd6da309c7163b39b380ef45886d0eb380307faa545c9f743333a13d20443
      ota_target_os: linux
      ota_runner: ubuntu-latest

  verify-container-linux:
    uses: ./.github/workflows/ota-verify-container-linux.yml
    with:
      ota_projection_identity: sha256:a220f763df18ac8914b8d8f809ffcecaec1d6b8993a8f18b23cf809165986c86
      ota_target_os: linux
      ota_runner: ubuntu-latest
